### PR TITLE
fix(display): quick fix for display on iOs

### PR DESCRIPTION
**Pull request by Oupsla**
This commit just remove a css rule to fix this issue :  https://github.com/convoo/login-fire/issues/97

### CODE REVIEW

**Comment by masonlouchart** [comment]
It's looks good but there still is an issue with the word _"or"_ that is not properly aligned. Maybe we should fix it in the same time.

capture d ecran 2017-06-15 a 07 33 28

**Comment by masonlouchart** [comment]
OK, I added the CSS rule `line-height: 0px;` on the span and increase the `padding` of the _div_ to 16px.


capture d ecran 2017-06-15 a 07 38 43

If it's looks good for you, could you add those changes in your PR please?

**Comment by Oupsla** [comment]
Done right now :)

**Review by masonlouchart — APPROVED** [review]
LGTM.

**Pull request merged**
