### PR TITLE
Fix login-fire-form width changes on error

### PR DESCRIPTION
**Pull request by masonlouchart**
- restructures the source code of the `login-fire-form` element
- fixes issue #115

### CODE REVIEW

**Comment by sbeleidy** [comment]
Would we ever need a login-fire-form with the wide attribute through login-fire?

**Review by sbeleidy — APPROVED** [review]

**Comment by sbeleidy** [comment]
I had the following issues but not sure if this would belong in another PR:


```
Unable to find a suitable version for firebase, please choose one by typing one of the numbers below:
    1) firebase#>= 3.5.1 < 4.0 which resolved to 3.9.0 and is required by polymerfire#0.10.4
    2) firebase#^4.1.1 which resolved to 4.1.3 and is required by polymerfire#2.1.0

Prefix the choice with ! to persist it to bower.json

? Answer 2

Unable to find a suitable version for app-storage, please choose one by typing one of the numbers below:
    1) app-storage#^0.10.0 which resolved to 0.10.0 and is required by polymerfire#0.10.4
    2) app-storage#1 - 2 which resolved to 2.0.2 and is required by polymerfire#2.1.0

Prefix the choice with ! to persist it to bower.json

? Answer 2

Unable to find a suitable version for hydrolysis, please choose one by typing one of the numbers below:
    1) hydrolysis#hydrolysis-1.x which resolved to c4caa3d19f and is required by iron-component-page#2.0.0
    2) hydrolysis#^1.18 which resolved to 1.24.1 and is required by iron-component-page#1.1.9

Prefix the choice with ! to persist it to bower.json

? Answer 2

Unable to find a suitable version for iron-location, please choose one by typing one of the numbers below:
    1) iron-location#^0.8.0 which resolved to 0.8.11 and is required by iron-demo-helpers#1.2.6
    2) iron-location#1 - 2 which resolved to 2.0.1 and is required by iron-demo-helpers#2.0.0

Prefix the choice with ! to persist it to bower.json

? Answer 2

Unable to find a suitable version for mocha, please choose one by typing one of the numbers below:
    1) mocha#^2.3.0 which resolved to 2.5.3 and is required by web-component-tester#4.3.6
    2) mocha#^3.1.2 which resolved to 3.4.2 and is required by web-component-tester#6.0.0

Prefix the choice with ! to persist it to bower.json

? Answer 2

Unable to find a suitable version for test-fixture, please choose one by typing one of the numbers below:
    1) test-fixture#^1.0.0 which resolved to 1.1.2 and is required by web-component-tester#4.3.6
    2) test-fixture#^3.0.0-rc.1 which resolved to 3.0.0-rc.1 and is required by web-component-tester#6.0.0

Prefix the choice with ! to persist it to bower.json

? Answer 2

Please note that,
    polymer#1.9.1 depends on webcomponentsjs#^0.7.24 which resolved to webcomponentsjs#0.7.24
    login-fire depends on webcomponentsjs#^v1.0.0 which resolved to webcomponentsjs#1.0.1
Resort to using webcomponentsjs#^1.0.0 which resolved to webcomponentsjs#1.0.1
Code incompatibilities may occur.
```

**Comment by masonlouchart** [comment]
I added the "wide" attribute because of the demo. But I agree, we don't need to manage this kind of style.

Do you want I remove it?

_I'll check if I have the same behavior during the installation_

**Comment by masonlouchart** [comment]
It was merged indeed.

**Comment by masonlouchart** [comment]
Damn it! I merged this one because it was approved but there were still questions (about "wide" attribute and dependencies)... 😕

**Comment by masonlouchart** [comment]
No question during the installation for me.

**Comment by sbeleidy** [comment]
I don't fully understand what the wide attribute is being used for tbh.

@bkawk, what do you think of having this attribute and how would you want to use it?

**Comment by masonlouchart** [comment]
I added this attribute because before the fix, the form was filling its parent by default. Now, its width is limited. So on the demo called "Wide form bal-bla-bla" I had to make the form filling its parent. IMO, we could removed this "useless" attribute and the demo.

**Pull request closed without merging**
