### PR TITLE
Made login-fire a hybrid element

### PR DESCRIPTION
**Pull request by Protoss78**
Should fix issue #84 
Following changes were implemented:

- Reworked dependencies according to current Polymer 2.0 hybrid element documentation
- Renamed shared-styles to login-fire-styles, because of styling problems when tested in PSK app
- Fixed text compution problems in login-fire-button and when tested in PSK Polymer 1.x app
- Set default appName to blank, because of another computation error in Polymer 1.x hybrid mode 
- Fixed problem with hiding icons in login-form-button in 1.x hybrid mode by adding [hidden] class

Known issue: 
The demo pages currently do not work, but this seems to be a problem with iron-component-page. I could reproduce the same error by checking out the current paper-slider 2.0 preview.
An issue is already reported here: https://github.com/Polymer/polymer-cli/issues/610

### CODE REVIEW

**Comment by sbeleidy** [comment]
Hey @Protoss78, thanks for the contribution!

When you say the demo pages do not work, what do you mean exactly?

**Comment by Protoss78** [comment]
You're welcome. 👍 
When you install polymer-cli 2.0, clone the repo and start polymer serve in the project root directory you should be able to see the Docs & API page as well as the demo page. These pages do not show up in the browser, because of various unresolvable links (webcomponents-loader.js, etc.). To me it looks like a problem with iron-component-page component - especially since other paper elements (paper-slider) seem to have the same problem.

**Comment by sbeleidy** [comment]
What I'm confused about is that it seemed to work fine for me. That's why I wasn't sure I was testing it properly or looking for the right error. I'll try again and check the issue.

**Comment by Protoss78** [comment]
Ah ok. Maybe the problem is related to my installed polymer-cli@next version then. I'll update it and try again as well.

**Comment by H-Plus-Time** [comment]
Seems to work on my end as well (polymer-cli 0.18.2). There is one other potential cause (aside from polymer-cli@next) - when the version conflicts at `bower install` occured, what resolutions did you set?

**Comment by Protoss78** [comment]
Yep works now for me too. Just updated my polymer-cli installation. Looks like that fixed it.

**Comment by masonlouchart** [comment]
Because this PR is not yet merged, we could try to use [Polymer stable 2.0.0](https://github.com/Polymer/polymer/releases/tag/v2.0.0)?

**Comment by Protoss78** [comment]
Yep. Totally agree. I will update the dependencies and the PR.

**Comment by Protoss78** [comment]
2.0 dependencies updated. Ready to go from my side. 😄

**Comment by masonlouchart** [comment]
My apologies, after reading again the content of the milestone for the v1, I'm thinking if we want a version running on Polymer 1 the dependency can't be Polymer 2 but [1.9.1](https://github.com/Polymer/polymer/releases/tag/v1.9.1).

I'm really sorry about this mistake. 🙇

**Comment by sbeleidy** [comment]
I get this conflict:

image

bower.json has the resolution but bower-1.x does not. Is this supposed to be the case?

**Comment by Protoss78** [comment]
@sbeleidy : I'll look into that problem after work today.

**Comment by Protoss78** [comment]
The webcomponents.js resolution error is fixed. The required resolution property was added on the wrong object level. The originally committed bower-1.x.json was removed, this file was created by a bower command and is not required by the hybrid element itself.

**Comment by Oupsla** [comment]
Any news on the merge of this PR ?

Sometimes I got a problem when I click on the facebook button (app completly frozen) and I think this is related to old dependencies.

**Comment by masonlouchart** [comment]
LGTM but this PR must be carefully tested because of the dependencies. It's in the stack 😉

**Comment by sbeleidy** [comment]
I think #117 caused conflicts with this but should be an easy fix. Aside from that, can we get more feedback from people trying this with Polymer 2? Has anyone had any issues?

**Comment by Protoss78** [comment]
I've fixed the merge conflict and updated the app-localize-behavior dependency to #^1.0.0.

**Comment by masonlouchart** [comment]
@Protoss78 Thank you 👍

**Comment by Protoss78** [comment]
@masonlouchart You're welcome :grin:

**Comment by masonlouchart** [comment]
I'm reviewing this PR and I encountered install issue with Polymer 2 version.

capture d ecran 2017-06-22 a 23 33 46

I think the first resolution question is due to the "reverse-element" element. Maybe we could try to move it to Polymer 1.9.

For the second resolution issue, I think it's due to the fact Bower download Polymer 1.9 and Polymer 2 which have different version requirement. It seems the resolutions of the variant (with Polymer 1.9) are used when we try to install the default dependencies (with Polymer 2)... 😕 

_Edit 1:_
We have the [reverse-element](https://github.com/convoo/reverse-element) in dependencies that is not a hybrid element. It requires Polymer 1.9 so when we try to install the default version of `login-fire` Bower is asking to choose the Polymer version, of course!

> To run on both 1.x and 2.x, hybrid elements should only depend on other hybrid elements

**Comment by masonlouchart** [comment]
_It was a mistake to merge the missing import and the issue with the custom property as default value. My apologies_ 🙇 

To no have trouble during the install step, a hybrid version of the [reverse-element](https://github.com/convoo/reverse-element) must be released.

I checked the element twice or more by Polymer's version and also on different devices with [BrowserStack](https://www.browserstack.com). I think it's ready!

If anyone want check, go ahead and enjoy the party! 🕺

**Comment by masonlouchart** [comment]
I would like to say that the first merge [f86d581](https://github.com/convoo/login-fire/pull/94/commits/f86d5810feda9643873cb99b0d4c448921f181b9) (and the others after that) should not have be done.

IMHO, due to the bunch of missing changes, the PR should have to be aborted, the branch rebased and a new PR proposed. Because we already have merged the branches the PR is kind of useless. 

We just have screwed up the Git history with empty merge commits.

__Some resources I like well:__
- [A succesful Git branching model considered harmful](https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful)
- [A stable mainline branching model for Git](http://www.bitsnbites.eu/a-stable-mainline-branching-model-for-git/)

Did you read them? What is your opinion about them? 👨‍🎓

**Comment by stemuk** [comment]
@masonlouchart While my skills with Git are rather limited, the suggestions you made regarding rebasing the branch and proposing a new PR seem very logical to me. Has there already been progress on that regard or do you need any help?

**Comment by masonlouchart** [comment]
@stemuk For the opened PRs I think we'll merge them without rebasing. But I guess we should add a description of this kind of situation to the "Contributing" section (in the README file).

_PS: In my company we always rebase feature branches before merge them._

**Pull request merged**
