### PR TITLE
Version 1.0.0 Release

### PR DESCRIPTION
**Pull request by sbeleidy**

### CODE REVIEW

**Comment by sbeleidy** [comment]
Let's discuss if we're missing anything after also merging #129 and fixing the conflicts.

**Comment by masonlouchart** [comment]
Just to have the situation in mind, here the list of commits that are on the `master` branch and not on the `v2`:

capture d ecran 2017-07-25 a 23 00 12

And the issues on the milestone "v1" that are not solved:

capture d ecran 2017-07-25 a 23 05 06

**Comment by masonlouchart** [comment]
# Tests sign-in Anonymously and Google

All tests on another device than my Macbook Pro _(OSX 10.12.5)_ was made with [BrowserStack](https://www.browserstack.com).

On Chrome I have also tested the form (sign-in, sign-up, bad password format, email already used and forgotten password).

## _"unbuilt"_ version

I have simply ran the command `polymer serve`.

- OSX 10.12.5 with Chrome 59.0.3071.115 🆗 
- OSX 10.12.5 with Firefox 54.0.1 🆗 
- OSX 10.12.5 with Safari 10.1.1 🆗 
- Nexus 6 Android 5 with Chrome 🆗 
- Galaxy S6 Android 5 with embed browser 🆗 
- iPhone 6S iOS 9 with Safari 🆗 
- iPhone 6 iOS 8 with Safari 🆗 
- Windows 10 with Opera 45 🆗 
- Windows 10 with Edge 14 🆗 
- Windows 10 with IE11 ⚠️  => works but the displaying little bit broken.
- Windows 8.1 with IE11 ❌ => can't sign-in with Google, dialog window not shown then a Firebase error is received. I suspect the VM for the dialog window resulting to a timeout error.

## built version

I have ran the command `polymer build --bundle && polymer serve --root build/default`.

- OSX 10.12.5 with Chrome 59.0.3071.115 🆗 
- OSX 10.12.5 with Firefox 54.0.1 ❌  => not working at all due to WebComponents.
- OSX 10.12.5 with Safari 10.1.1 🆗 

## Attachements
Windows 10 with IE11 (unbuilt version):
capture d ecran 2017-07-26 a 00 47 17

Windows 8.1 with IE11 (unbuilt version):
capture d ecran 2017-07-26 a 00 55 02

OSX 10.12.5 with Firefox 54.0.1 (built version):
capture d ecran 2017-07-26 a 01 05 02


_There is missing tests but I'm going to sleep a bit before start my day work._ 🛌

**Review by bkawk — COMMENTED** [review]
When the social button are all single or double lines, it looks great, but when the social buttons have some single and some double line it looks ugly. Is there any way to force the providers name on to the second line, if 1 or more are double lined?

screen shot 2017-11-20 at 9 10 04 am

**Comment by masonlouchart** [comment]
It's easier (and I would prefer) to force one-line style.

**Review by masonlouchart — APPROVED** [review]

**Pull request merged**
