### PR TITLE
Initial adding of logout-fire 

### LINKED ISSUE #40: Look into logout button as component
There may be a way to logout the use with a button using https://firebase.google.com/docs/reference/node/firebase.auth.Auth#signOut . the issue is that it might not update the user and signedIn status of the login-fire components. We should look into it and test it out.

signOut function as part of login-fire should not be removed in favor of this but (if it works) this may make it simpler for some users.

### PR DESCRIPTION
**Pull request by sbeleidy**
Closes #40. Let me know what else you think we should add to it.

### CODE REVIEW

**Comment by bkawk** [comment]
On the Demo for "Debug login-fire Demo with all options" can we remove the "LOG OUT" button as we now have the "Sign Out" button

**Comment by sbeleidy** [comment]
I think this may be related to just removing the debug section completely? #44 

Or are you suggesting we just remove logout from the debug section in general?

**Comment by bkawk** [comment]
I was just suggesting we remove logout from the debug section as we now have the sign out button, is there any need for both?

#44 I'm not sure wich way to go on yet, keeping the debug is usefull and existing users may want/need it and on the flip side once done using it there is no need for it to be there.

**Comment by sbeleidy** [comment]
The need for both would be if you're not using logout-fire and you still want to debug things. That allows you to debug without adding and importing an extra component. You could also be using your own way to sign out (eg. sign out from a dropdown) and don't need logout-fire.

On the other hand, you could just add the extra component for debugging then remove it later.

**Comment by sbeleidy** [comment]
Let's figure out how this should change based on the discussion in #47 and based on how it may be redundant with `login-fire-button`

**Pull request closed without merging**
