### PR TITLE
Add French to locales

### PR DESCRIPTION
**Pull request by masonlouchart**
This commit adds the French translations into the "locales.json"
file and the according demo.

### CODE REVIEW

**Comment by masonlouchart** [comment]
🇫🇷 French talk too much I guess... They broke our buttons!

capture d ecran 2017-03-26 a 17 43 33

**Comment by sbeleidy** [comment]
Hey @LM450N, that's awesome! Thanks for adding!

Could you also add a custom style to the french demo to change the min-width of the buttons so it appears all on one line?

**Comment by masonlouchart** [comment]
I'm thinking buttons should not have a `min-with` but a `white-space: nowrap` instead. For the `login-fire-social` the column of buttons should take the wiser width. User will able to limit the `max-width`.

What about it?

**Comment by LM450N** [comment]
I tried it but not so easy. Because the child elements can't be found at the read/attached callback of the `login-fire-social`. Maybe it will be possible with a little delay but it's definitively not a good idea. So, I'll push a commit with custom style 😉

**Comment by sbeleidy** [comment]
I think it looks great! Was there anything else you wanted to add or is this ready to merge?

image

**Comment by masonlouchart** [comment]
@sbeleidy Nope, I done!

**Pull request merged**
